---
  - fail:
      msg:
        - "puppet agent version {{ puppet_version }} is not valide"
        - "puppet agent version should be in (6,7)"
    when: puppet_version not in ('6','7')

  - name: "Install Repo for Puppet {{ puppet_version }}"
    apt:
       deb: "{{ puppet_release }}"
       state: present
    environment: "{{ proxy_env }}"
    notify: Update cache
    when: 
    - use_proxy is defined
    - use_proxy
    - install_from_puppetlabs

  - name: "Install Repo for Puppet {{ puppet_version }}"
    apt:
       deb: "{{ puppet_release }}"
       state: present
    notify: Update cache
    when: 
      - (use_proxy is not defined) or (not use_proxy)
      - install_from_puppetlabs

  - name: "Install Puppet Agent {{ puppet_version }}"
    apt:
        name: "{{ puppet_packages }}"
        state: present
    environment: "{{ proxy_env }}"
    when: 
      - use_proxy is defined
      - use_proxy

  - name: "Install Puppet Agent {{ puppet_version }}"
    apt:
        name: "{{ puppet_packages }}"
        state: present
    when: (use_proxy is not defined) or (not use_proxy)

  - name: "Get server facter fqdn"
    command: "hostname -f"
    changed_when: no
    register: HostName
    ignore_errors: yes

  - name: "Copy Puupet Conf file"
    template: src=puppet.conf.j2 dest=/etc/puppetlabs/puppet/puppet.conf mode=644
    notify:
      - Shutdown Puppet agent
      - Start Puppet agent
    when: not puppet_agent_certification

  - name: "Copy Puupet Conf file"
    template: src=puppet.conf.j2 dest=/etc/puppetlabs/puppet/puppet.conf mode=644
    notify:
      - Shutdown Puppet agent
      - Delete puppet Certificat files
      - Generate puppet CA
      - Start Puppet agent
    when: puppet_agent_certification        