---
# tasks file for katelloDeploye
- name: include distribution dependency variables
  include_vars: "{{ item }}"
  with_items:
    - "{{ ansible_distribution_file_variety }}.yml"

- name: install libselinux-python
  yum:
    name: libselinux-python
    state: present
  environment: "{{ proxy_env }}"
  when: ( ansible_distribution_file_variety == "RedHat" and ansible_distribution_major_version == "6")

- name: Install and configure puppet agent
  include_tasks: "{{ ansible_distribution_file_variety }}-puppet_agent_install.yml"