---
- fail:
    msg:
      - "puppet agent version {{ puppet_version }} is not valide"
      - "puppet agent version should be in (6,7)"
  when: puppet_version not in ('6','7')

- name: "Install Repo for Puppet {{ puppet_version }}"
  yum:
    name: "{{ puppet_release }}"
    state: present
    disable_gpg_check: yes
  environment: "{{ proxy_env }}"
  when: 
    - use_proxy is defined
    - use_proxy
    - install_from_puppetlabs

- name: "Install Repo for Puppet {{ puppet_version }}"
  yum:
    name: "{{ puppet_release }}"
    state: present
    disable_gpg_check: yes
  when: 
    - (use_proxy is not defined) or (not use_proxy)
    - install_from_puppetlabs

- name: "Install Puppet Agent {{ puppet_version }}"
  yum:
    name: "{{ puppet_packages }}"
    state: present
  environment: "{{ proxy_env }}"
  when: 
    - use_proxy is defined
    - use_proxy

- name: "Install Puppet Agent {{ puppet_version }}"
  yum:
    name: "{{ puppet_packages }}"
    state: present
  when: (use_proxy is not defined) or (not use_proxy)

- name: "Get server hostname"
  command: "hostname"
  changed_when: no
  register: HostName

- name: "Copy Puupet Conf file"
  template: src=puppet.conf.j2 dest=/etc/puppetlabs/puppet/puppet.conf mode=644
  notify:
    - Shutdown Puppet agent
    - Start Puppet agent
  when: not puppet_agent_certification

- name: "Copy Puupet Conf file"
  template: src=puppet.conf.j2 dest=/etc/puppetlabs/puppet/puppet.conf mode=644
  notify:
    - Shutdown Puppet agent
    - Delete puppet Certificat files
    - Generate puppet CA
    - Start Puppet agent
  when: puppet_agent_certification    